language: python
python:
  - "3.4"
  - "3.5"

install:
  - "pip install ."
  - "npm install"
  - "npm install webpack -g"

script:
  - "cd docs && make dirhtml ; cd .."
  ## The $PATH seems to need to be re-inforced here rather than in the 'before_install' stage.
  - "python setup.py test"

## Cache the pip install (which is minimal at the moment), and the phantomjs install.
cache:
  pip: []
